spring:
  devtools:
    livereload:
      enabled: 'true'
    restart:
      enabled: 'true'
  freemarker:
    cache: 'false'
  thymeleaf:
    cache: 'false'
    check-template-location: 'true'
    prefix=classpath: '/templates/'
    suffix: '.html'
  datasource:
    hikari:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbcUrl: jdbc:log4jdbc:mariadb://mariajhjo:3306/test_db3?useUnicode=true&characterEncoding=utf-8
      jdbcUrl: jdbc:log4jdbc:mariadb://localhost:3306/test_db3?useUnicode=true&characterEncoding=utf-8
      username: test_jhjo
      password: '1234'
  jpa:
    driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://mariajhjo:3306/test_db2?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mariadb://localhost:3306/test_db3?useUnicode=true&characterEncoding=utf-8
    username: test_jhjo
    password: '1234'
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update

mybatis:
  type-aliases-package: com.study.jhjoTL.model
  mapper-location:
    classpath: com.study.jhjoTL.mappers/*.xml
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG
